----
title: "concept_generation"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(LaplacesDemon)
library(glmnetUtils)
library(glue)
library(gsignal)
library(patchwork)
library(ranger)
library(scico)
library(tidyverse)
my_theme <- theme_classic() +
  theme()
theme_set(my_theme)
set.seed(20240201)
```

```{r}
rbloom <- function(n_time = 50, lambda = 3, win_len = 9, r = 0.9, alpha = 0.4) {
  n_bloom <- max(rpois(1, lambda), 1)
  bloom_times <- sample(seq(win_len, n_time - win_len), n_bloom)
  y <- vector(length = n_time)
  for (i in seq_along(bloom_times)) {
    ix <- seq(bloom_times[i] - win_len / 2, bloom_times[i] + win_len / 2)
    y[ix] <- y[ix] + tukeywin(win_len + 1, r)
  }
  alpha * n_time * y / sum(y)
}

rincrease <- function(n_time = 50, n_steps = 25, alpha = 0.3) {
  rtrajectory(n_time = n_time, n_steps = n_steps, alpha = alpha, increase = TRUE)
}

rdecrease <- function(n_time = 50, n_steps = 25, alpha = 0.3) {
  rtrajectory(n_time = n_time, n_steps = n_steps, alpha = alpha, increase = FALSE)
}

rtrajectory <- function(n_time = 50, n_steps = 25, alpha = 0.5, increase = TRUE) {
  if (increase) {
    steps <- 1 * upper.tri(matrix(1, n_time, n_time))
  } else {
    steps <- 1 * lower.tri(matrix(1, n_time, n_time))
  }
  steps <- steps[seq(1, nrow(steps), length = n_steps), ]
  u <- rdirichlet(1, rep(alpha, n_steps))
  y <- u %*% steps
  n_time * y / sum(y)
}

plot_trajectory <- function(ys) {
  as_tibble(ys) |>
    mutate(time = row_number()) |>
    pivot_longer(-time) |>
    mutate(name = str_remove(name, "V")) |>
    ggplot() +
    geom_line(aes(time, value), linewidth = 1.2) +
    facet_wrap(~ reorder(name, value), ncol = 5)
}

subcommunities <- function(n_sub = 5, n_taxa = 50, alpha = 0.9) {
  rdirichlet(n_sub, rep(alpha, n_taxa))
}

p <- list()
p[["bloom"]] <- sapply(1:10, \(i) rbloom()) |>
  plot_trajectory() +
  labs(title = "(a) Pure Blooms")
p[["decreases"]] <- sapply(1:10, \(i) rdecrease()) |>
  plot_trajectory() +
  labs(title = "(b) Pure Decreasing Trajectories")

x <- subcommunities()
p[["subcommunities"]] <- as.data.frame(x) |>
  mutate(Factor = row_number()) |>
  pivot_longer(-Factor, names_to = "Sample") |>
  mutate(
    Sample = str_remove(Sample, "V"),
    Sample = factor(Sample, levels = hclust(dist(t(x)))$order),
    Factor = factor(Factor, levels = hclust(dist(x))$order)
  ) |>
  ggplot() +
    geom_tile(aes(Sample, Factor, fill = value, col = value)) +
    scale_x_discrete(expand = c(0, 0)) +
    scale_y_discrete(expand = c(0, 0)) +
    scale_fill_scico(palette = "berlin", midpoint = 0.06) +
    scale_color_scico(palette = "berlin", midpoint = 0.06) +
    labs(title = c("(c) Factor Contributions"))
```

```{r}
n_samples <- 500
n_concepts <- 25
n_timepoints <- 50
n_taxa <- 144
k_clusters <- 24
```

```{r}
concept_weights <- rdirichlet(n_samples, rep(1, n_concepts))
concepts <- list()
for (k in seq_len(n_concepts)) {
  cur_taxa <- sample(n_taxa, n_taxa * 0.3)
  x <- matrix(runif(n_timepoints * n_taxa, 0, 0.05), n_timepoints, n_taxa)
  f <- sample(c(rbloom, rincrease, rdecrease), 1)
  x[, cur_taxa] <- sapply(seq_along(cur_taxa), \(i) f[[1]]())
  concepts[[k]] <- x
}

samples <- list()
for (i in seq_len(n_samples)) {
  samples[[i]] <- matrix(0, n_timepoints, n_taxa)
  for (k in seq_len(n_concepts)) {
    samples[[i]] <- samples[[i]] + concept_weights[i, k] * concepts[[k]]
  }
}

samples <- map_dfr(samples, ~ as_tibble(.) |> mutate(time = row_number()), .id = "subject") |>
  pivot_longer(starts_with("V"), names_to = "taxon") |>
  mutate(
    subject = glue("subject_{subject}"),
    taxon = str_replace(taxon, "V", "tax")
  )

samples |>
  filter(taxon %in% glue("tax{1:10}")) |>
  ggplot() +
  geom_line(aes(time, value, group = subject), linewidth = 0.2, alpha = 0.5) +
  facet_wrap(~ taxon)
```

```{r}
matching <- c(rep("healthy", k_clusters / 2), rep("disease", k_clusters / 2))
assignments <- kmeans(concept_weights, centers = k_clusters)$cluster
concept_weights <- concept_weights |>
  as_tibble() |>
  mutate(
    subject = glue("subject_{row_number()}"),
    class = matching[assignments],
    assignments = factor(assignments)
    ) |>
  pivot_longer(starts_with("V"), names_to = "concept", values_to = "weight")
```

```{r, fig.width=12, fig.height=4}
merged_samples <- concept_weights |>
  select(subject, assignments, class) |>
  unique() |>
  left_join(samples)

p[["samples"]] <- merged_samples |>
  filter(
    taxon %in% glue("tax{1:10}"),
    subject %in% glue("subject_{40:55}")
#    assignments %in% c(1:5, 20:24)
  ) |>
  mutate(taxon = str_replace(taxon, "tax", "Species ")) |>
  ggplot() +
  geom_line(aes(time, value, col = class, group = subject), alpha = 0.9, linewidth = 0.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_color_manual(values = c("#730739", "#4BA68C")) +
  labs(x = "Time", y = "Abundance", col = "Group") +
  guides(color = guide_legend(override.aes = list(linewidth = 2))) +
  facet_wrap(~ reorder(taxon, value), scales = "free_y", ncol = 5) +
  theme(
    axis.title = element_text(size = 16),
    strip.text = element_text(size = 14),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 14)
  ) +
  labs(title = c("(d) Simulated Trajectories"))
```

```{r}
merged_samples |>
  select(subject, taxon, time, value, class) |>
  rename(Freq = value) |>
  pivot_wider(names_from = c("taxon", "time"), values_from = "Freq") |>
  write_csv("data/blooms.csv")
```

```{r}
concept_weights |>
  select(subject, concept, weight) |>
  unique() |>
  mutate(weight = 1 * (weight > 0.05)) |>
  pivot_wider(names_from = "concept", values_from = "weight") |>
  write_csv("data/concepts.csv")
```

```{r}
xy <- merged_samples |>
  select(class, subject, time, taxon, value) |>
  pivot_wider(names_from = c("taxon", "time")) |>
  mutate(class = factor(class)) |>
  select(-subject)

fit_rf <- ranger(class ~ ., data = xy)
fit_rf

fit_glm <- cv.glmnet(class ~ ., xy, family = "binomial")
y_hat <- predict(fit_glm, xy)
data.frame(y = xy$class, y_hat = ifelse(y_hat[, 1] > 0, "healthy", "disease")) |>
  count(y, y_hat)
```

```{r}
(p[["bloom"]] + p[["decreases"]]) / 
  p[["subcommunities"]] /
  p[["samples"]] +
  plot_layout(heights = c(1, 1, 1.5))
ggsave("data/example_trajectories.png", width = 12, height = 8)
```