---
title: "Linear Data Generation"
output: rmdformats::readthedown
---

```{r}
knitr::opts_chunk$set(warnings = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(glue)
```

First we set some data generating parameters.

```{r}
n_subjects <- 100
n_taxa <- 300
n_timepoints <- 25
nonnull <- seq_len(n_taxa / 4)
alpha <- 1
slope <- 2 / n_timepoints
```

This will generate the data with the first `nonnull` taxa with a linearly
increasing slope over time.
```{r}
shape <- c(n_subjects, n_taxa, n_timepoints)
lambda <- array(rgamma(prod(shape), alpha), shape)
samples_mat <- array(0, shape)

for (i in seq_len(n_subjects)) {
  lambda_i <- lambda[i, , ]
  for (j in seq_len(n_taxa)) {
    if (j %in% nonnull & i <= n_subjects / 2) {
      lambda_i <- lambda_i + matrix(1, nrow = n_taxa, ncol = 1) %*% matrix(slope * seq_len(n_timepoints), nrow = 1)
    }
    samples_mat[i, j, ] <- rpois(n_timepoints, lambda_i[j, ])
  }
}

#lambda[seq_len(n_subjects / 2), nonnull, ] <- lambda[seq_len(n_subjects / 2), nonnull, ] +
#  slope * seq_len(n_timepoints)
dimnames(samples_mat) <- list(
  glue("subject_{1:n_subjects}"),
  glue("tax_{1:n_taxa}"),
  glue("{1:n_timepoints}")
)
```

Let's reshape into a long data.frame and save the output.
```{r}
samples <- as.data.frame.table(samples_mat) |>
  rename(subject = Var1, taxon = Var2, time = Var3) |>
  mutate(
    time = as.numeric(time),
    class = ifelse(subject %in% glue("subject_{1:(n_subjects/2)}"), "disease", "healthy")
  )

write_csv(samples, "data/linear.csv")
```