---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(glue)
theme_set(theme_classic())
set.seed(20240203)
```

```{r}
n_taxa <- 144
n_timepoints <- 50
tax_id <- "tax21"

feature_names <- apply(expand.grid(glue("tax{1:n_taxa}"), as.character(1:n_timepoints)), 1, paste, collapse = "_")
attributions <- read_csv("data/attributions.csv") |>
  set_names(feature_names)

blooms <- read_csv("data/blooms.csv")
classes <- blooms |>
  select(subject, class) |>
  unique() |>
  pull(class)
```

```{r}
attr_subset <- attributions |>
  mutate(subject = row_number(), class = classes[1:63]) |>
  select(subject, class, starts_with(tax_id))

hclust_res <- attr_subset |>
  select(starts_with("tax")) |>
  dist() |>
  hclust()

attr_subset |>
  pivot_longer(-subject:-class, names_to = "feature") |>
  separate(feature, c("taxon", "timepoint")) |>
  mutate(
    timepoint = as.integer(str_extract(timepoint, "[0-9]+")),
    subject = factor(subject, hclust_res$order)
  ) |>
  ggplot() +
  geom_tile(aes(timepoint, subject, fill = value)) +
  scale_fill_gradient2() +
  scale_x_continuous(expand = c(0, 0))
```

```{r}
attr75 <- attributions |>
  mutate(subject = glue("subject_{row_number()}")) |>
  pivot_longer(-subject, names_to = "feature", values_to = "attribution") |>
  filter(str_detect(feature, tax_id)) |>
  mutate(time = as.integer(str_extract(feature, "[0-9]+$")))
```


```{r}
subset_str <- glue("subject_{c(6, 63, hclust_res$order[seq(2, 62, length.out = 6)])}")
blooms |>
  filter(subject %in% subset_str) |>
  select(subject, class, starts_with(tax_id)) |>
  pivot_longer(starts_with(tax_id), values_to = "Freq", names_to = "feature") |>
  left_join(attr75) |>
  mutate(
    subject = str_remove(subject, "subject_"),
    subject = factor(subject, str_remove(subset_str, "subject_"))
  ) |>
  ggplot(aes(time, Freq)) +
  geom_line(aes(group = subject, col = class), linewidth = 0.9) +
  scale_color_manual(values = c("#730739", "#4BA68C")) +
  geom_point(aes(size = abs(attribution), shape = attribution > 0)) +
  scale_size_area(max_size = 16, guide = "none") +
  scale_shape_manual(values = c(95, 43), guide = "none") +
  facet_wrap(~subject, scales = "free_y", nrow = 2) +
  labs(x = "Time", y = "Abundance", title = "IG for Species 21") +
  theme(strip.text.y = element_text(angle = 0))

ggsave("data/integrated_gradients.png", width = 8, height = 3)
```

```{r}
blooms |>
  select(subject, class, starts_with(tax_id)) |>
  pivot_longer(starts_with(tax_id), names_to = "feature", values_to = "Freq") |>
  mutate(time = as.integer(str_extract(feature, "[0-9]+$"))) |>
  ggplot() +
  geom_line(
    aes(time, Freq, group = subject),
    linewidth = 0.2, col = "#0c0c0c", alpha = 0.8
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  facet_grid(class ~ .)
```

