---
title: "R Notebook"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(rpart.plot)
library(glue)
my_theme <- theme_classic() +
  theme()
theme_set(my_theme)
set.seed(20240201)
source("interpretable.R")
```

```{r}
samples <- read_csv("../data/blooms.csv") |>
  mutate(class = factor(class))
p_hat <- read_csv("../data/p_hat.csv")
colnames(p_hat) <- c("index", "prob")
p_hat <- p_hat |>
  mutate(subject = glue("subject_{index + 1}"))

xy <- samples |>
  left_join(p_hat) |>
  select(-subject, -index)
```

```{r}
problem_rec <- recipe(prob ~ ., data = select(xy, -class)) |>
  update_role(prob, new_role = "outcome") |>
  step_normalize(all_numeric())

wf <- workflow() |>
  add_recipe(problem_rec)

tree_spec <- decision_tree(cost_complexity = tune()) |>
  set_engine("rpart") |>
  set_mode("regression")

tree_outputs(tree_spec, wf, select(xy, -class), "rmse")
```

```{r}
problem_rec <- recipe(class ~ ., data = select(xy, -prob)) |>
  update_role(class, new_role = "outcome") |>
  step_normalize(all_numeric())
wf <- workflow() |>
  add_recipe(problem_rec)
tree_spec <- decision_tree(cost_complexity = tune()) |>
  set_engine("rpart") |>
  set_mode("classification")

tree_outputs(tree_spec, wf, select(xy, -prob))
```
